
import io
import json

from dotenv import load_dotenv
from langchain.chat_models import init_chat_model
from langgraph.graph import END, START, StateGraph
from PIL import Image
from pydantic import BaseModel, Field
from typing_extensions import TypedDict

load_dotenv()

GENERAL_LLM = init_chat_model(model="gemini-3.1-flash-lite", model_provider="google_genai")

####################################################################
#              1. CLASSIFIER STATES
####################################################################

class ProductClassifierState(TypedDict):
    """State carried through the product-selection workflow."""

    product_name_list: list[str]
    product_info_list: list[str]
    culture_summary: str
    articles_summary: str
    top_candidates: list[str]
    feedback: str


####################################################################
#              2. VALIDATION MODELS
####################################################################

class ProductClassifierCandidate(BaseModel):
    """Select the best matching products using the target culture and news context."""

    top_candidates: list[str] = Field(
        description=(
            "Given the product list, choose up to 5 product names that best fit the "
            "target culture and the latest articles summary. Only return product names "
            "that already exist in the provided product list. Do not invent products."
        )
    )


class ProductClassifierFeedback(BaseModel):
    """Critique the current candidate list and explain what should be improved."""

    feedback: str = Field(
        description=(
            "Evaluate the selected top candidate products against the culture summary and "
            "article summary, then give concise critical feedback that can be used to "
            "improve the next selection round."
        )
    )


class ProductClassifierImprovedCandidate(BaseModel):
    """Use the feedback to refine the candidate selection when needed."""

    top_candidates: list[str] = Field(
        description=(
            "Given the product list and the earlier feedback, choose the best possible set "
            "of up to 5 product names that better match the target culture and article "
            "context. Only return product names that already exist in the product list."
        )
    )


####################################################################
#              3. FETCH / LOAD NODE
####################################################################

def fetch_products(state: ProductClassifierState):
    """Load the product catalog generated by the product extraction step."""
    with open("products.json", "r", encoding="utf-8") as file:
        product_catalog = json.load(file)

    product_names = [product.get("name", "") for product in product_catalog if product.get("name")]

    return {"product_name_list": product_names, "product_info_list":str(product_catalog)}


####################################################################
#              4. PROCESSOR NODES
####################################################################

def select_candidate_products(state: ProductClassifierState):
    """Choose the best product candidates based on culture and market signals."""
    product_name_list = state["product_name_list"]
    culture_summary = state["culture_summary"]
    articles_summary = state["articles_summary"]
    product_info_list = state["product_info_list"]
    prompt = (
        "Product name list:\n"
        f"{product_name_list}\n\n"
        "Product full info list:\n"
        f"{product_info_list}\n\n"
        "Culture summary:\n"
        f"{culture_summary}\n\n"
        "Articles summary:\n"
        f"{articles_summary}\n\n"
        "Select the top 5 products that best fit this target culture and the recent news context."
    )

    product_classifier_llm = GENERAL_LLM.with_structured_output(ProductClassifierCandidate)
    result = product_classifier_llm.invoke([{"role": "user", "content": prompt}])
    return {"top_candidates": result.top_candidates}


def evaluate_product_candidates(state: ProductClassifierState):
    """Assess the current candidate list and provide constructive feedback."""
    product_name_list = state["product_name_list"]
    product_info_list = state["product_info_list"]
    culture_summary = state["culture_summary"]
    articles_summary = state["articles_summary"]
    top_candidates = state["top_candidates"]

    prompt = (
        "Product list:\n"
        f"{product_name_list}\n\n"
        "Product full info list:\n"
        f"{product_info_list}\n\n"
        "Culture summary:\n"
        f"{culture_summary}\n\n"
        "Articles summary:\n"
        f"{articles_summary}\n\n"
        "Current top candidates:\n"
        f"{top_candidates}\n\n"
        "Review the selected products critically and explain what should be improved before "
        "finalizing the final shortlist."
    )

    product_classifier_llm = GENERAL_LLM.with_structured_output(ProductClassifierFeedback)
    result = product_classifier_llm.invoke([{"role": "user", "content": prompt}])
    return {"feedback": result.feedback}


def improve_product_candidates(state: ProductClassifierState):
    """Refine the shortlist using the feedback from the previous selection round."""
    product_name_list = state["product_name_list"]
    product_info_list = state["product_info_list"]

    culture_summary = state["culture_summary"]
    articles_summary = state["articles_summary"]
    feedback = state["feedback"]

    prompt = (
        "Product list:\n"
        f"{product_name_list}\n\n"
        "Product full info list:\n"
        f"{product_info_list}\n\n"
        "Culture summary:\n"
        f"{culture_summary}\n\n"
        "Articles summary:\n"
        f"{articles_summary}\n\n"
        "Previous feedback:\n"
        f"{feedback}\n\n"
        "Improve the candidate selection using this feedback while keeping only valid product names from the list."
    )

    product_classifier_llm = GENERAL_LLM.with_structured_output(ProductClassifierImprovedCandidate)
    result = product_classifier_llm.invoke([{"role": "user", "content": prompt}])
    return {"top_candidates": result.top_candidates}


####################################################################
#              5. PRODUCT CLASSIFIER GRAPH CONSTRUCTION
####################################################################

product_classifier_graph = StateGraph(ProductClassifierState)
product_classifier_graph.add_node("fetch_products", fetch_products)
product_classifier_graph.add_node("select_candidate_products", select_candidate_products)
product_classifier_graph.add_node("evaluate_product_candidates", evaluate_product_candidates)
product_classifier_graph.add_node("improve_product_candidates", improve_product_candidates)

product_classifier_graph.add_edge(START, "fetch_products")
product_classifier_graph.add_edge("fetch_products", "select_candidate_products")
product_classifier_graph.add_edge("select_candidate_products", "evaluate_product_candidates")
product_classifier_graph.add_edge("evaluate_product_candidates", "improve_product_candidates")
product_classifier_graph.add_edge("improve_product_candidates", END)

compiled_product_classifier_graph = product_classifier_graph.compile()


####################################################################
#              6. IMPORT BUILD
####################################################################

def build_product_classifier_agent():
    """Build the uncompiled product classifier graph."""
    product_classifier_graph = StateGraph(ProductClassifierState)
    product_classifier_graph.add_node("fetch_products", fetch_products)
    product_classifier_graph.add_node("select_candidate_products", select_candidate_products)
    product_classifier_graph.add_node("evaluate_product_candidates", evaluate_product_candidates)
    product_classifier_graph.add_node("improve_product_candidates", improve_product_candidates)

    product_classifier_graph.add_edge(START, "fetch_products")
    product_classifier_graph.add_edge("fetch_products", "select_candidate_products")
    product_classifier_graph.add_edge("select_candidate_products", "evaluate_product_candidates")
    product_classifier_graph.add_edge("evaluate_product_candidates", "improve_product_candidates")
    product_classifier_graph.add_edge("improve_product_candidates", END)
    return product_classifier_graph


####################################################################
#              7. Saving Graph Images
####################################################################
def save_products_classifer_agent_graph_png():
    """Export the product classifier graph as a PNG image."""
    graph_bytes = io.BytesIO(compiled_product_classifier_graph.get_graph().draw_mermaid_png())

    with Image.open(graph_bytes) as img:
        img.save("product_classifier_agent_graph.png")
