name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" 
      
      - name: Install Dependencies
        run: uv sync


      - name: Build Application
        run: uv build


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  test:
    needs: build # This guarantees 'test' only runs after 'build' succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" 
      
      - name: Install Dependencies
        run: uv sync

      - name: Run Pytest
        run: uv run pytest
        env:
          EMAIL: ${{ secrets.EMAIL }}
          GEMINI_API_KEY : ${{ secrets.GEMINI_API_KEY }}

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      # 1. Pull the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Download the compiled dist/ artifact (if built in a separate job)
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      # 3. Configure SSH access to your EC2 instance
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      # 4. Copy project files or dist/ to EC2
      - name: Copy files to EC2
        run: |
          rsync -avz --exclude '.git' ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app/

      # 5. Execute commands on EC2 (Install dependencies & restart app)
      - name: Deploy and restart application
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'


            #install uv
            curl -LsSf https://astral.sh/uv/install.sh | sh
  
            cd /home/ubuntu/app/dist
            uv venv
            source .venv/bin/activate

            # Sync dependencies on EC2 using uv
            uv sync 

            tar -xzf e_commerical_langgraph_fastapi-0.1.0.tar.gz

            cd /home/ubuntu/app/dist/e_commerical_langgraph_fastapi-0.1.0/src/e_commerical_langgraph_fastapi/services

            # moving service to systemctl
            sudo mv deploy_service.service /etc/systemd/system/

            # install nginx
            sudo apt update && sudo apt install nginx -y

            # removing default nginx page
            sudo rm /etc/nginx/sites-enabled/default

            # create symbolic link
            sudo ln -s  /nginx/nginx.conf /etc/nginx/sites-enabled/

            # restart systemctl
            sudo systemctl daemon-reload

            # run nginx
            sudo systemctl start nginx

            # run custom service
            sudo systemctl start deploy_service.service

            
          EOF